// Placeholder product data — will be replaced with Shopify API data

const DUMMY_PRODUCTS = [
  {
    id: '1',
    name: "Hardrace K Swap Engine Mount Kit (Civic EK '96–'00)",
    brand: 'Hardrace',
    sku: 'HR-Q0752',
    price: 1052.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/HR-Q0752.png',
    href: '/products/hardrace-k-swap-mount-kit-ek',
    description: 'Six-piece mount kit for K-series swaps into Civic EK chassis. 5mm thick steel alloy brackets with CNC aluminium mounts and reinforced rubber bushings.',
    category: 'Engine',
    subcategory: 'Mounts',
    vehicles: ['Civic EK (96–00)'],
    tags: ['engine mount', 'k-swap', 'civic', 'ek'],
    backorder: true,
  },
  {
    id: '2',
    name: "Hardrace K Swap Engine Mount Kit (Accord Euro CL9 '03–'07)",
    brand: 'Hardrace',
    sku: 'HR-Q1096',
    price: 1052.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/HR-Q1096.png',
    href: '/products/hardrace-k-swap-mount-kit-cl9',
    description: "Six-piece set compatible with Accord Euro TSX CL9 '03–'07 manual gearbox. Superior strength with steel alloy brackets and solid rubber bushings.",
    category: 'Engine',
    subcategory: 'Mounts',
    vehicles: ['Accord CL9 (03–07)'],
    tags: ['engine mount', 'k-swap', 'accord', 'cl9'],
  },
  {
    id: '3',
    name: "Hardrace K Swap Engine Mount Kit (EG/DC2 '92–'01)",
    brand: 'Hardrace',
    sku: 'HR-Q1095',
    price: 1052.00,
    originalPrice: 1150.00,
    image: 'https://elusiveracing.com.au/wp-content/uploads/HR-Q1095.png',
    href: '/products/hardrace-k-swap-mount-kit-eg-dc2',
    description: 'Five-piece mount assembly for EG Civic and Integra DC2 platforms. Eliminates unwanted vibrations with reinforced bushings and aluminium mounts.',
    category: 'Engine',
    subcategory: 'Mounts',
    vehicles: ['Civic EG (92–95)', 'Integra DC2 (94–01)'],
    tags: ['engine mount', 'k-swap', 'integra', 'dc2', 'eg'],
  },
  {
    id: '4',
    name: "Hardrace K Swap Engine Mount Kit (EG/EH '92–'95, DC2 '94–'01)",
    brand: 'Hardrace',
    sku: 'HR-Q0751',
    price: 999.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/HR-Q0751.png',
    href: '/products/hardrace-k-swap-mount-kit-eg-eh',
    description: 'Five-piece kit for older EG/EH Civic and early DC2 Integra. Compatible with DC5/EP3 manual gearboxes with steel alloy construction.',
    category: 'Engine',
    subcategory: 'Mounts',
    vehicles: ['Civic EG (92–95)', 'Integra DC2 (94–01)'],
    tags: ['engine mount', 'k-swap', 'civic', 'eg', 'eh'],
  },
  {
    id: '5',
    name: 'Honda OEM K24 CL9 Vehicle Speed Sensor Washer',
    brand: 'Honda OEM',
    sku: '90401-RAS-000',
    price: 10.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/90401-RAS-000.png',
    href: '/products/honda-oem-vss-washer-k24',
    description: 'Genuine Honda OEM sealing washer for the Vehicle Speed Sensor (VSS) on K24 engines in the Accord Euro CL9. Prevents oil leaks around the sensor housing.',
    category: 'Drivetrain',
    subcategory: 'Accessories',
    vehicles: ['Accord CL9 (03–07)'],
    tags: ['oem', 'sensor', 'k24', 'accord', 'cl9'],
  },
  {
    id: '6',
    name: '4 Piston Ultra High Polish Timing Chain (K20/K24)',
    brand: '4 Piston',
    sku: '4P-HPTC',
    price: 785.00,
    originalPrice: 870.00,
    image: 'https://elusiveracing.com.au/wp-content/uploads/4P-HPTC-K20-K24.png',
    href: '/products/4-piston-timing-chain-k20-k24',
    description: 'Ultra-high polish finish timing chain for K20 and K24 engines. Pins have less friction making them last longer and stretch less when paired with PEEK chain guides.',
    category: 'Engine',
    subcategory: 'Chains, Belts & Tensioners',
    vehicles: ['Civic EK (96–00)', 'Civic EG (92–95)', 'Integra DC2 (94–01)', 'Integra DC5 (02–06)'],
    tags: ['timing chain', 'k20', 'k24', 'engine'],
    backorder: true,
  },
  {
    id: '7',
    name: '4 Piston Timing Chain Tensioner (K20/K24)',
    brand: '4 Piston',
    sku: '4P-TCTEN-K20-K24',
    price: 700.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/4P-TCTEN-K20-K24.png',
    href: '/products/4-piston-timing-chain-tensioner-k20-k24',
    description: 'Hydraulic tensioner with internal mechanical safety stop for motorsport applications. Compatible with both K20 and K24 engines.',
    category: 'Engine',
    subcategory: 'Chains, Belts & Tensioners',
    vehicles: ['Civic EK (96–00)', 'Civic EG (92–95)', 'Integra DC2 (94–01)', 'Integra DC5 (02–06)'],
    tags: ['timing chain', 'tensioner', 'k20', 'k24', 'engine'],
  },
  {
    id: '8',
    name: 'Hasport Billet Performance Rear Mount (Civic FD2/FN2)',
    brand: 'Hasport',
    sku: 'FDRR',
    price: 265.00,
    originalPrice: 310.00,
    image: 'https://elusiveracing.com.au/wp-content/uploads/FDRR.png',
    href: '/products/hasport-rear-mount-fd2-fn2',
    description: 'Billet aluminium performance rear engine mount for 2006–2011 Honda Civic Si FD2/FN2. Available in four stiffness options from street to full race.',
    category: 'Engine',
    subcategory: 'Mounts',
    vehicles: ['Civic FD2/FN2 (06–11)'],
    tags: ['engine mount', 'civic', 'fd2', 'fn2', 'billet'],
  },
  {
    id: '9',
    name: 'Honda OEM Civic EK Roof Moulding – Left',
    brand: 'Honda OEM',
    sku: '74316-S03-003',
    price: 217.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/74306-S03-003-1.png',
    href: '/products/honda-oem-ek-roof-moulding-left',
    description: "Genuine Honda OEM roof moulding strip for the Civic EK – driver's side (left). Replaces faded or missing OEM trim for a factory-fresh finish.",
    category: 'Body & Accessories',
    subcategory: 'Exterior',
    vehicles: ['Civic EK (96–00)'],
    tags: ['oem', 'body', 'civic', 'ek', 'exterior'],
  },
  {
    id: '10',
    name: 'Honda OEM Civic EK Roof Moulding – Right',
    brand: 'Honda OEM',
    sku: '74306-S03-003',
    price: 217.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/74306-S03-003.png',
    href: '/products/honda-oem-ek-roof-moulding-right',
    description: 'Genuine Honda OEM roof moulding strip for the Civic EK – passenger side (right). Direct OEM replacement for a clean, factory-correct exterior.',
    category: 'Body & Accessories',
    subcategory: 'Exterior',
    vehicles: ['Civic EK (96–00)'],
    tags: ['oem', 'body', 'civic', 'ek', 'exterior'],
  },
  {
    id: '11',
    name: 'Honda OEM Integra DC5 Roof Moulding – Left',
    brand: 'Honda OEM',
    sku: '74316-S6M-003',
    price: 260.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/74316-S6M-003.png',
    href: '/products/honda-oem-dc5-roof-moulding-left',
    description: "Genuine Honda OEM roof moulding for the Integra DC5 – driver's side (left). Exact factory fitment with OEM-grade adhesive backing.",
    category: 'Body & Accessories',
    subcategory: 'Exterior',
    vehicles: ['Integra DC5 (02–06)'],
    tags: ['oem', 'body', 'integra', 'dc5', 'exterior'],
  },
  {
    id: '12',
    name: 'Honda OEM Integra DC5 Roof Moulding – Right',
    brand: 'Honda OEM',
    sku: '74306-S6M-003',
    price: 260.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/74306-S6M-003.png',
    href: '/products/honda-oem-dc5-roof-moulding-right',
    description: 'Genuine Honda OEM roof moulding for the Integra DC5 – passenger side (right). Replaces cracked or missing factory trim with an exact OEM part.',
    category: 'Body & Accessories',
    subcategory: 'Exterior',
    vehicles: ['Integra DC5 (02–06)'],
    tags: ['oem', 'body', 'integra', 'dc5', 'exterior'],
    backorder: true,
  },
  {
    id: '13',
    name: 'Honda OEM F20C Oil Pump Chain Guide',
    brand: 'Honda OEM',
    sku: '13460-PCX-003',
    price: 44.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/13460PCX003.png',
    href: '/products/honda-oem-f20c-oil-pump-chain-guide',
    description: 'Genuine Honda OEM oil pump chain guide for the F20C engine found in the S2000. Keeps the oil pump chain aligned and prevents premature wear.',
    category: 'Engine',
    subcategory: 'Chains, Belts & Tensioners',
    vehicles: ['S2000 AP1/AP2'],
    tags: ['oem', 'chain guide', 'f20c', 's2000'],
  },
  {
    id: '14',
    name: 'Honda OEM F-Series Coilpack',
    brand: 'Honda OEM',
    sku: '30520-PCX-007',
    price: 223.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/30520-pcx-007-1.png',
    href: '/products/honda-oem-f-series-coilpack',
    description: 'Genuine Honda OEM ignition coilpack for F-series engines including the S2000 F20C. Direct OEM replacement for misfires or worn coils.',
    category: 'Engine',
    subcategory: 'Accessories',
    vehicles: ['S2000 AP1/AP2'],
    tags: ['oem', 'coilpack', 'ignition', 'f20c', 's2000'],
    backorder: true,
  },
  {
    id: '15',
    name: 'Honda OEM K20 Transmission 4th Gear Counter Shaft',
    brand: 'Honda OEM',
    sku: '23481-PNT-000',
    price: 214.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/23481-PNT-000.png',
    href: '/products/honda-oem-k20-4th-gear-counter-shaft',
    description: 'Genuine Honda OEM 4th gear counter shaft for K20 transmissions. OEM replacement for worn or damaged gears during gearbox rebuilds.',
    category: 'Drivetrain',
    subcategory: 'Gears & Final Drive',
    vehicles: ['Civic EK (96–00)', 'Integra DC2 (94–01)', 'Integra DC5 (02–06)'],
    tags: ['oem', 'gearbox', 'k20', 'transmission', '4th gear'],
  },
  {
    id: '16',
    name: 'Honda OEM K20 Transmission 3rd Gear Counter Shaft',
    brand: 'Honda OEM',
    sku: '23471-PNS-000',
    price: 239.00,
    originalPrice: 265.00,
    image: 'https://elusiveracing.com.au/wp-content/uploads/23471-PNS-000-1.png',
    href: '/products/honda-oem-k20-3rd-gear-counter-shaft',
    description: 'Genuine Honda OEM 3rd gear counter shaft for K20 transmissions. Essential for gearbox rebuilds where synchro or gear teeth are worn.',
    category: 'Drivetrain',
    subcategory: 'Gears & Final Drive',
    vehicles: ['Civic EK (96–00)', 'Integra DC2 (94–01)', 'Integra DC5 (02–06)'],
    tags: ['oem', 'gearbox', 'k20', 'transmission', '3rd gear'],
  },
  {
    id: '17',
    name: 'Honda OEM Idle Air Control Valve O-Ring Seal (B-Series)',
    brand: 'Honda OEM',
    sku: '36455-PT3-A01',
    price: 17.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/36455-PT3-A01.jpg',
    href: '/products/honda-oem-iacv-o-ring-b-series',
    description: 'Genuine Honda OEM O-ring seal for the Idle Air Control Valve on B-series engines. Stops vacuum leaks causing rough idle or erratic RPM.',
    category: 'Engine',
    subcategory: 'Gaskets',
    vehicles: ['Civic EK (96–00)', 'Civic EG (92–95)', 'Integra DC2 (94–01)'],
    tags: ['oem', 'o-ring', 'iacv', 'b-series', 'gasket'],
  },
  {
    id: '18',
    name: 'Honda OEM Civic EK Indicators (Pair)',
    brand: 'Honda OEM',
    sku: '33851-S2H-KIT',
    price: 176.00,
    originalPrice: 210.00,
    image: 'https://elusiveracing.com.au/wp-content/uploads/33851-S2H-SET.png',
    href: '/products/honda-oem-ek-indicators-pair',
    description: 'Genuine Honda OEM front indicator set for the Civic EK. Includes both driver and passenger side. Factory-correct fitment and lens clarity.',
    category: 'Body & Accessories',
    subcategory: 'Exterior',
    vehicles: ['Civic EK (96–00)'],
    tags: ['oem', 'indicators', 'lights', 'civic', 'ek', 'exterior'],
  },
  {
    id: '19',
    name: 'Honda OEM Civic FN2R Tailgate Boot Strut',
    brand: 'Honda OEM',
    sku: '74820-SMT-E02',
    price: 160.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/74820-SMT-E02.png',
    href: '/products/honda-oem-fn2r-tailgate-strut',
    description: 'Genuine Honda OEM tailgate boot strut for the Civic FN2R hatchback. Replaces weak or failed gas struts that no longer hold the boot open.',
    category: 'Body & Accessories',
    subcategory: 'Accessories',
    vehicles: ['Civic FD2/FN2 (06–11)'],
    tags: ['oem', 'tailgate', 'boot strut', 'civic', 'fn2'],
  },
  {
    id: '20',
    name: 'Honda OEM K-Series VTEC Oil Control Valve O-Ring',
    brand: 'Honda OEM',
    sku: '15832-PNA-023',
    price: 12.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/honda-15832-pna-023-image-1.jpg',
    href: '/products/honda-oem-k-series-vtec-ocv-o-ring',
    description: 'Genuine Honda OEM O-ring for the VTEC Oil Control Valve on K-series engines. A common source of oil leaks around the OCV — cheap fix before it becomes a big mess.',
    category: 'Engine',
    subcategory: 'Gaskets',
    vehicles: ['Civic EK (96–00)', 'Integra DC2 (94–01)', 'Integra DC5 (02–06)', 'Accord CL9 (03–07)'],
    tags: ['oem', 'o-ring', 'vtec', 'ocv', 'k-series', 'gasket'],
  },
  {
    id: '21',
    name: 'Circuit Hero Lower Timing Chain Guide Type-II (K20/K24)',
    brand: 'Circuit Hero',
    sku: 'CH-LTCG-K',
    price: 95.00,
    originalPrice: null,
    image: 'https://elusiveracing.com.au/wp-content/uploads/f16cc36a-f7e9-469f-9044-083a13da0456.webp',
    href: '/products/circuit-hero-timing-chain-guide-k20-k24',
    description: 'Circuit Hero Type-II lower timing chain guide for K20 and K24 engines. Upgraded billet design prevents chain walk at high RPM. A must for high-revving K-swaps.',
    category: 'Engine',
    subcategory: 'Chains, Belts & Tensioners',
    vehicles: ['Civic EK (96–00)', 'Civic EG (92–95)', 'Integra DC2 (94–01)', 'Integra DC5 (02–06)'],
    tags: ['chain guide', 'k20', 'k24', 'timing', 'circuit hero'],
  },
  {
    id: '22',
    name: 'Hybrid Racing K-Series Serpentine Belt',
    brand: 'Hybrid Racing',
    sku: 'HYB-BLT-00-01',
    price: 55.00,
    originalPrice: 68.00,
    image: 'https://elusiveracing.com.au/wp-content/uploads/HYB-BLT-00-01-image-1.webp',
    href: '/products/hybrid-racing-k-series-serpentine-belt',
    description: 'Hybrid Racing replacement serpentine belt for K-series engine swaps. Correct length and tooth pitch for K20/K24 accessory drive setups in EG, EK, and DC2 chassis.',
    category: 'Engine',
    subcategory: 'Chains, Belts & Tensioners',
    vehicles: ['Civic EK (96–00)', 'Civic EG (92–95)', 'Integra DC2 (94–01)'],
    tags: ['belt', 'serpentine', 'k-series', 'k20', 'k24', 'hybrid racing'],
  },
];

export default DUMMY_PRODUCTS;
