FROM node:20-alpine
WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
RUN corepack enable && yarn install

COPY . .

# Declare build-time args for Vite (must be declared as ARG to be available during RUN yarn build)
ARG VITE_WC_URL
ARG VITE_WC_CONSUMER_KEY
ARG VITE_WC_CONSUMER_SECRET
ARG VITE_SHOPIFY_STORE_DOMAIN
ARG VITE_SHOPIFY_STOREFRONT_TOKEN
ARG VITE_MEILISEARCH_HOST
ARG VITE_MEILISEARCH_SEARCH_KEY
ARG VITE_STRIPE_PUBLISHABLE_KEY
ARG VITE_PAYPAL_CLIENT_ID
ARG VITE_SENTRY_DSN
ARG VITE_APP_VERSION
ARG VITE_AFTERPAY_ENABLED
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_ORG
ARG SENTRY_PROJECT

ENV VITE_WC_URL=$VITE_WC_URL
ENV VITE_WC_CONSUMER_KEY=$VITE_WC_CONSUMER_KEY
ENV VITE_WC_CONSUMER_SECRET=$VITE_WC_CONSUMER_SECRET
ENV VITE_SHOPIFY_STORE_DOMAIN=$VITE_SHOPIFY_STORE_DOMAIN
ENV VITE_SHOPIFY_STOREFRONT_TOKEN=$VITE_SHOPIFY_STOREFRONT_TOKEN
ENV VITE_MEILISEARCH_HOST=$VITE_MEILISEARCH_HOST
ENV VITE_MEILISEARCH_SEARCH_KEY=$VITE_MEILISEARCH_SEARCH_KEY
ENV VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY
ENV VITE_PAYPAL_CLIENT_ID=$VITE_PAYPAL_CLIENT_ID
ENV VITE_SENTRY_DSN=$VITE_SENTRY_DSN
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_AFTERPAY_ENABLED=$VITE_AFTERPAY_ENABLED
ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
ENV SENTRY_ORG=$SENTRY_ORG
ENV SENTRY_PROJECT=$SENTRY_PROJECT

RUN yarn build

ENV PORT=8080
EXPOSE 8080
CMD ["node", "server.js"]
